name: FastTransfer
version: 1.0.3
api: [3.0.0]
main: shoghicp\FastTransfer\FastTransfer
load: STARTUP
author: [shoghicp, robske_110]
website: "https://github.com/robske_110/FastTransfer"
description: "Transfer vanilla Minecraft: PE clients to another server"
commands:
 transfer:
  permission: fasttransfer.command.transfer
  usage: "/transfer [player] <address> <port>"
permissions:
 fasttransfer.command.transfer:
  description: "Allows to transfer players to another server"
  default: op
